name: Deploy React application to production

on:
  pull_request:
    branches: [ "main" ]

jobs:
  install-and-build:
    name: Install dependencies and sync files on VPS
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_BASE_URL_API_V1=${{ vars.BASE_URL_API_V1 }}
          VITE_JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
        run: npm run build

      - name: Compress dist folder into tar file
        run: tar -czf dist.tar.gz dist

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "dist.tar.gz"
          target: ${{ secrets.FOLDER_PATH }}

  update-repository:
    name: Update the repository on the VPS
    runs-on: ubuntu-22.04
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ${{ secrets.FOLDER_PATH }}
            git pull origin main

  update-dependencies-on-vps:
    name: Unzip dist.tar.gz on the VPS
    runs-on: ubuntu-22.04
    needs: install-and-build
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        name: Update the repository on the VPS
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ${{ secrets.FOLDER_PATH }}
            rm -rf dist
            tar -xzf dist.tar.gz
            rm dist.tar.gz
            echo "icjlex.academy deploy successsfully!"
